//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeregrineWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Information
    {
        public int CIK { get; set; }
        public string Name { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City___State { get; set; }
        public string Phone { get; set; }
        public int SIC { get; set; }
    }
}
