//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeregrineWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PeregrineResearchDatabaseEntities : DbContext
    {
        public PeregrineResearchDatabaseEntities()
            : base("name=PeregrineResearchDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CentralIndexKey> CentralIndexKeys { get; set; }
        public virtual DbSet<Clean_datum> Clean_Data { get; set; }
        public virtual DbSet<Company_Information> Company_Information { get; set; }
        public virtual DbSet<Peregrine_Result> Peregrine_Results { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<SIC_Code> SIC_Codes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
    }
}
